apiVersion: apps/v1
kind: Deployment
metadata:
  name: website2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website2
  template:
    metadata:
      labels:
        app: website2
    spec:
      containers:
      - name: website2
        image: jabin95/antique-website1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website2-service
spec:
  selector:
    app: website2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
